INSERT INTO
    `sticker` (
        `stickerId`,
        `packageId`,
        `stickerName`,
        `stickerImg`
    )
VALUES
    (
        12,
        2,
        'axolotl1',
        'packages/amphibian/axolotl1.png'
    ),
    (
        13,
        2,
        'axolotl2',
        'packages/amphibian/axolotl2.png'
    ),
    (
        14,
        2,
        'axolotl3',
        'packages/amphibian/axolotl3.png'
    ),
    (
        15,
        2,
        'blackrainfrog1',
        'packages/amphibian/blackrainfrog1.png'
    ),
    (
        16,
        2,
        'blackrainfrog2',
        'packages/amphibian/blackrainfrog2.png'
    ),
    (17, 2, 'eggs', 'packages/amphibian/eggs.png'),
    (18, 2, 'frog', 'packages/amphibian/frog.png'),
    (19, 2, 'frog2', 'packages/amphibian/frog2.png'),
    (20, 2, 'frog3', 'packages/amphibian/frog3.png'),
    (21, 2, 'frog4', 'packages/amphibian/frog4.png'),
    (22, 2, 'frog5', 'packages/amphibian/frog5.png'),
    (
        23,
        2,
        'gymnophiona',
        'packages/amphibian/gymnophiona.png'
    ),
    (
        24,
        2,
        'salamander',
        'packages/amphibian/salamander.png'
    ),
    (
        25,
        2,
        'salamander2',
        'packages/amphibian/salamander2.png'
    ),
    (
        26,
        2,
        'salamander3',
        'packages/amphibian/salamander3.png'
    ),
    (
        27,
        3,
        'birthdaycake',
        'packages/celebration/birthdaycake.png'
    ),
    (
        28,
        3,
        'bowtie',
        'packages/celebration/bowtie.png'
    ),
    (
        29,
        3,
        'camera',
        'packages/celebration/camera.png'
    ),
    (
        30,
        3,
        'candle',
        'packages/celebration/candle.png'
    ),
    (31, 3, 'candy', 'packages/celebration/candy.png'),
    (
        32,
        3,
        'chocolatebox',
        'packages/celebration/chocolatebox.png'
    ),
    (
        33,
        3,
        'confetti',
        'packages/celebration/confetti.png'
    ),
    (
        34,
        3,
        'confetti2',
        'packages/celebration/confetti2.png'
    ),
    (35, 3, 'crown', 'packages/celebration/crown.png'),
    (
        36,
        3,
        'discoball',
        'packages/celebration/discoball.png'
    ),
    (
        37,
        3,
        'garland',
        'packages/celebration/garland.png'
    ),
    (
        38,
        3,
        'musicalnotes',
        'packages/celebration/musicalnotes.png'
    ),
    (
        39,
        3,
        'partyhat',
        'packages/celebration/partyhat.png'
    ),
    (
        40,
        3,
        'pinata',
        'packages/celebration/pinata.png'
    ),
    (
        41,
        3,
        'present',
        'packages/celebration/present.png'
    ),
    (
        42,
        4,
        'qozb_1',
        'packages/crayon_shinchan_1/qozb_1.png'
    ),
    (
        43,
        4,
        'qozb_4',
        'packages/crayon_shinchan_1/qozb_4.png'
    ),
    (
        45,
        4,
        'qozb_12',
        'packages/crayon_shinchan_1/qozb_12.png'
    ),
    (
        46,
        4,
        'qozb_13',
        'packages/crayon_shinchan_1/qozb_13.png'
    ),
    (
        47,
        4,
        'qozb_43',
        'packages/crayon_shinchan_1/qozb_43.png'
    ),
    (
        48,
        4,
        'qozc8',
        'packages/crayon_shinchan_1/qozc8.png'
    ),
    (
        49,
        4,
        'qozc12',
        'packages/crayon_shinchan_1/qozc12.png'
    ),
    (
        50,
        4,
        'qozc13',
        'packages/crayon_shinchan_1/qozc13.png'
    ),
    (
        51,
        4,
        'qozc15',
        'packages/crayon_shinchan_1/qozc15.png'
    ),
    (
        52,
        4,
        'qozc18',
        'packages/crayon_shinchan_1/qozc18.png'
    ),
    (
        53,
        4,
        'qozc19',
        'packages/crayon_shinchan_1/qozc19.png'
    ),
    (
        54,
        5,
        'qozb_2',
        'packages/crayon_shinchan_2/qozb_2.png'
    ),
    (
        55,
        5,
        'qozb_3',
        'packages/crayon_shinchan_2/qozb_3.png'
    ),
    (
        56,
        5,
        'qozb_6',
        'packages/crayon_shinchan_2/qozb_6.png'
    ),
    (
        57,
        5,
        'qozb_8',
        'packages/crayon_shinchan_2/qozb_8.png'
    ),
    (
        58,
        5,
        'qozb_9',
        'packages/crayon_shinchan_2/qozb_9.png'
    ),
    (
        59,
        5,
        'qozb_14',
        'packages/crayon_shinchan_2/qozb_14.png'
    ),
    (
        60,
        5,
        'qozb_22',
        'packages/crayon_shinchan_2/qozb_22.png'
    ),
    (
        61,
        5,
        'qozb_46',
        'packages/crayon_shinchan_2/qozb_46.png'
    ),
    (
        62,
        5,
        'qozc9',
        'packages/crayon_shinchan_2/qozc9.png'
    ),
    (
        63,
        5,
        'qozc27',
        'packages/crayon_shinchan_2/qozc27.png'
    ),
    (
        64,
        5,
        'qozc50',
        'packages/crayon_shinchan_2/qozc50.png'
    ),
    (65, 6, 'beagle', 'packages/dogs/beagle.png'),
    (66, 6, 'beagle2', 'packages/dogs/beagle2.png'),
    (
        67,
        6,
        'bordercollie',
        'packages/dogs/bordercollie.png'
    ),
    (68, 6, 'boxer', 'packages/dogs/boxer.png'),
    (
        69,
        6,
        'chihuahua',
        'packages/dogs/chihuahua.png'
    ),
    (70, 6, 'corgi', 'packages/dogs/corgi.png'),
    (
        71,
        6,
        'frenchbulldog',
        'packages/dogs/frenchbulldog.png'
    ),
    (
        72,
        6,
        'greatdane',
        'packages/dogs/greatdane.png'
    ),
    (
        73,
        6,
        'miniatureschnauzer',
        'packages/dogs/miniatureschnauzer.png'
    ),
    (74, 6, 'pitbull', 'packages/dogs/pitbull.png'),
    (
        75,
        6,
        'pomeranian',
        'packages/dogs/pomeranian.png'
    ),
    (76, 6, 'poodle', 'packages/dogs/poodle.png'),
    (77, 6, 'samoyed', 'packages/dogs/samoyed.png'),
    (78, 6, 'shibainu', 'packages/dogs/shibainu.png'),
    (79, 7, 'beer', 'packages/frog/beer.png'),
    (
        80,
        7,
        'brokenheart',
        'packages/frog/brokenheart.png'
    ),
    (
        81,
        7,
        'celebration',
        'packages/frog/celebration.png'
    ),
    (82, 7, 'rich', 'packages/frog/rich.png'),
    (83, 7, 'sick', 'packages/frog/sick.png'),
    (84, 7, 'stress', 'packages/frog/stress.png'),
    (85, 7, 'tired', 'packages/frog/tired.png'),
    (86, 7, 'vacation', 'packages/frog/vacation.png'),
    (87, 7, 'workout', 'packages/frog/workout.png'),
    (
        88,
        8,
        'arrowandbow',
        'packages/heart_3d/arrowandbow.png'
    ),
    (
        89,
        8,
        'brokenheart',
        'packages/heart_3d/brokenheart.png'
    ),
    (
        90,
        8,
        'feelings',
        'packages/heart_3d/feelings.png'
    ),
    (
        91,
        8,
        'giftbox',
        'packages/heart_3d/giftbox.png'
    ),
    (92, 8, 'hearts', 'packages/heart_3d/hearts.png'),
    (
        93,
        8,
        'lovemessages',
        'packages/heart_3d/lovemessages.png'
    ),
    (
        94,
        8,
        'truelove',
        'packages/heart_3d/truelove.png'
    ),
    (
        95,
        9,
        'angry',
        'packages/human_emotions/angry.png'
    ),
    (
        96,
        9,
        'angry2',
        'packages/human_emotions/angry2.png'
    ),
    (
        97,
        9,
        'anxious',
        'packages/human_emotions/anxious.png'
    ),
    (
        98,
        9,
        'confident',
        'packages/human_emotions/confident.png'
    ),
    (
        99,
        9,
        'inlove',
        'packages/human_emotions/inlove.png'
    ),
    (
        100,
        9,
        'peaceful',
        'packages/human_emotions/peaceful.png'
    ),
    (
        101,
        9,
        'pensive',
        'packages/human_emotions/pensive.png'
    ),
    (
        102,
        9,
        'resentful',
        'packages/human_emotions/resentful.png'
    ),
    (
        103,
        9,
        'sick',
        'packages/human_emotions/sick.png'
    ),
    (
        104,
        9,
        'spiteful',
        'packages/human_emotions/spiteful.png'
    ),
    (
        105,
        9,
        'surprised',
        'packages/human_emotions/surprised.png'
    ),
    (106, 10, 'cake', 'packages/pixel_dot/cake.png'),
    (
        107,
        10,
        'cherry',
        'packages/pixel_dot/cherry.png'
    ),
    (108, 10, 'ghost', 'packages/pixel_dot/ghost.png'),
    (
        109,
        10,
        'hotdog',
        'packages/pixel_dot/hotdog.png'
    ),
    (
        110,
        10,
        'iwantpizza',
        'packages/pixel_dot/iwantpizza.png'
    ),
    (
        111,
        10,
        'loading',
        'packages/pixel_dot/loading.png'
    ),
    (112, 10, 'luigi', 'packages/pixel_dot/luigi.png'),
    (113, 10, 'mario', 'packages/pixel_dot/mario.png'),
    (114, 10, 'panda', 'packages/pixel_dot/panda.png'),
    (115, 10, 'pika', 'packages/pixel_dot/pika.png'),
    (
        116,
        10,
        'potatostick',
        'packages/pixel_dot/potatostick.png'
    ),
    (117, 10, 'ufo', 'packages/pixel_dot/ufo.png'),
    (
        118,
        10,
        'flower',
        'packages/pixel_dot/flower.png'
    ),
    (
        119,
        10,
        'icecream',
        'packages/pixel_dot/icecream.png'
    ),
    (120, 11, 'bell', 'packages/stuff_3d/bell.png'),
    (
        121,
        11,
        'beveledcone',
        'packages/stuff_3d/beveledcone.png'
    ),
    (
        122,
        11,
        'beveledcube',
        'packages/stuff_3d/beveledcube.png'
    ),
    (
        123,
        11,
        'camera',
        'packages/stuff_3d/camera.png'
    ),
    (
        124,
        11,
        'christmasgift',
        'packages/stuff_3d/christmasgift.png'
    ),
    (125, 11, 'light', 'packages/stuff_3d/light.png'),
    (
        126,
        11,
        'moneybag',
        'packages/stuff_3d/moneybag.png'
    ),
    (
        127,
        11,
        'pinkpencil',
        'packages/stuff_3d/pinkpencil.png'
    ),
    (
        128,
        11,
        'premiumquality',
        'packages/stuff_3d/premiumquality.png'
    ),
    (
        129,
        11,
        'target',
        'packages/stuff_3d/target.png'
    ),
    (
        130,
        11,
        'tesseract',
        'packages/stuff_3d/tesseract.png'
    ),
    (
        131,
        11,
        'trophy',
        'packages/stuff_3d/trophy.png'
    ),
    (
        132,
        12,
        'bootstrapframeworklogo',
        'packages/programming/bootstrapframeworklogo.png'
    ),
    (
        133,
        12,
        'clanguagelogo',
        'packages/programming/clanguagelogo.png'
    ),
    (
        134,
        12,
        'csslogo',
        'packages/programming/csslogo.png'
    ),
    (
        135,
        12,
        'dartprogramminglogo',
        'packages/programming/dartprogramminglogo.png'
    ),
    (
        136,
        12,
        'golanguagelogo',
        'packages/programming/golanguagelogo.png'
    ),
    (
        137,
        12,
        'javascriptlogo',
        'packages/programming/javascriptlogo.png'
    ),
    (
        138,
        12,
        'pythonlanguagelogo',
        'packages/programming/pythonlanguagelogo.png'
    ),
    (
        139,
        12,
        'rubylogo',
        'packages/programming/rubylogo.png'
    ),
    (140, 13, 'asap', 'packages/etc_3d/asap.png'),
    (
        141,
        13,
        'bitcoin',
        'packages/etc_3d/bitcoin.png'
    ),
    (
        142,
        13,
        'boyexplodingpartypopper',
        'packages/etc_3d/boyexplodingpartypopper.png'
    ),
    (
        143,
        13,
        'devilface',
        'packages/etc_3d/devilface.png'
    ),
    (
        144,
        13,
        'gang_hand',
        'packages/etc_3d/gang_hand.png'
    ),
    (
        145,
        13,
        'instagramlogo',
        'packages/etc_3d/instagramlogo.png'
    ),
    (
        146,
        13,
        'iosphotos',
        'packages/etc_3d/iosphotos.png'
    ),
    (
        147,
        13,
        'location',
        'packages/etc_3d/location.png'
    ),
    (
        148,
        13,
        'mcdonalds',
        'packages/etc_3d/mcdonalds.png'
    ),
    (
        149,
        13,
        'moneyheistpeople',
        'packages/etc_3d/moneyheistpeople.png'
    ),
    (
        150,
        13,
        'newnotification',
        'packages/etc_3d/newnotification.png'
    ),
    (151, 13, 'skull', 'packages/etc_3d/skull.png'),
    (
        152,
        13,
        'telegram1',
        'packages/etc_3d/telegram1.png'
    );