name: Deployment
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: yarn install
        working-directory: ${{ env.working-directory }}
      - name: Build page
        run: yarn build
        env:
          REACT_APP_SERVER_URL: "${{ secrets.REACT_APP_SERVER_URL }}"
        working-directory: ${{ env.working-directory }}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: "${{ secrets.TOKEN }}"
          publish_dir: client/build
